language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
install:
#    - pip install -r requirements.txt
    - pip install nose
    - python setup.py install
script:
    - nosetests

#language: python
#python:
#  - "2.7"
#  - "nightly"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
#script: nosetests
